kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: frontendlogger-fss
  namespace: pto
  labels:
    team: pto
  cluster: dev-fss
spec:
  image: docker.pkg.github.com/navikt/frontendlogger/frontendlogger:{{version}}
  ingresses:
    - https://frontendlogger-q0.nais.adeo.no
    - https://app-q0.adeo.no/frontendlogger
    - https://app-q0.dev.adeo.no/frontendlogger
    - https://modapp-q0.adeo.no/frontendlogger
    - https://frontendlogger-q1.nais.adeo.no
    - https://app-q1.adeo.no/frontendlogger
    - https://app-q1.dev.adeo.no/frontendlogger
    - https://modapp-q1.adeo.no/frontendlogger
    - https://frontendlogger.dev-fss-pub.nais.io
  port: 8080
  liveness:
    path: frontendlogger/internal/health/liveness
    initialDelay: 60
  readiness:
    path: frontendlogger/internal/health/readiness
    initialDelay: 60
  prometheus:
    enabled: true
    path: frontendlogger/internal/prometheus
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: "https://*.adeo.no"
