kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: frontendlogger-fss
  namespace: default
  labels:
    team: pto
  cluster: prod-fss
spec:
  image: docker.pkg.github.com/navikt/frontendlogger/frontendlogger:{{version}}
  ingresses:
    - https://frontendlogger.nais.adeo.no
    - https://app.adeo.no/frontendlogger
    - https://modapp.adeo.no/frontendlogger
  port: 8080
  liveness:
    path: frontendlogger/internal/isAlive
    initialDelay: 120
  readiness:
    path: frontendlogger/internal/isReady
    initialDelay: 120
  prometheus:
    enabled: true
    path: frontendlogger/internal/metrics
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: APP_ENVIRONMENT_NAME
      value: p
    - name: CORS_ALLOWED_ORIGINS
      value: "https://*.adeo.no"
